=== gagbo/flocking_sdl/data/schema_ant.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Ant",
    "description": "An ant agent",
    "type": "object",
    "properties": {
        "type": {
            "description": "Describe the type of Entity",
            "type": "string"
        },
        "size": {
            "description": "Size of the Ant in world units",
            "type": "array",
            "items": {
                "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
        },
        "friction_factor": {
            "description": "Friction factor with floor",
            "type": "number",
            "minimum": 0
        },
        "mass": {
            "description": "Mass of the ant",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "max_acceleration": {
            "description": "Maximum acceleration sustainable by agent",
            "type": "number",
            "minimum": 0
        },
        "cruise_speed": {
            "description": "Cruise speed the agent wants to be at",
            "type": "number",
            "minimum": 0
        },
        "vision": {
            "description": "Describes the vision of the agent",
            "type": "object",
            "properties": {
                "angle_degrees": {
                    "description": "Half-angle of vision in degrees",
                    "type": "number",
                    "minimum": 0
                },
                "distance": {
                    "description": "Vision range in world units",
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "angle_degrees",
                "distance"
            ]
        },
        "decision_weights": {
            "description": "Coefficients of the decisions of the agent",
            "type": "object",
            "properties": {
                "alignment": {
                    "description": "Have the same speed as everyone in sight",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "cohesion": {
                    "description": "Go where all other ants are",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "separation": {
                    "description": "Go away from other ants",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                }
            },
            "required": [
                "alignment",
                "cohesion",
                "separation"
            ]
        },
        "separation_potential_exponent": {
            "description": "Exponent for the separation potential between 2 agents",
            "type": "number",
            "minimum": 0
        },
        "world_situation": {
            "description": "Geographical situation of the agent",
            "type": "object",
            "properties": {
                "acceleration": {
                    "description": "Acceleration",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 2,
                    "maxItems": 2
                },
                "position": {
                    "description": "Position",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 2,
                    "maxItems": 2
                },
                "velocity": {
                    "description": "Velocity",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 2,
                    "maxItems": 2
                }
            },
            "required": [
                "position"
            ]
        },
        "colors": {
            "description": "Colors to paint the agent",
            "type": "object",
            "properties": {
                "blind": {
                    "description": "Color to use when no agent is in sight",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 4,
                    "maxItems": 4
                },
                "capped_force": {
                    "description": "Color to use when the agent is at max force",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 4,
                    "maxItems": 4
                },
                "default": {
                    "description": "Default color",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "minItems": 4,
                    "maxItems": 4
                }
            },
            "required": [
                "default",
                "capped_force",
                "blind"
            ]
        }
    },
    "required": [
        "mass",
        "friction_factor",
        "max_acceleration",
        "size",
        "type",
        "cruise_speed",
        "vision",
        "decision_weights",
        "separation_potential_exponent",
        "world_situation",
        "colors"
    ]
}

=== gagbo/flocking_sdl/data/ant_default.json
{
   "type" : "Ant",
   "size" :
   [
       5.0,
       5.0
   ],
   "friction_factor" : 0.0,
   "mass" : 1.0,
   "max_acceleration" : 0.0005,
   "cruise_speed" : 5.0,
   "vision" :
   {
      "angle_degrees" : 60.0,
      "distance" : 125.0
   },
   "decision_weights" :
   {
      "alignment" : 0.60000002384185791,
      "cohesion" : 0.10000000149011612,
      "separation" : 0.30000001192092896
   },
   "separation_potential_exponent" : 0.5,
   "world_situation" :
   {
      "acceleration" :
      [
          0.0,
          0.0
      ],
      "position" :
      [
          252.03352180301297,
          381.54048984341028
      ],
      "velocity" :
      [
          0.0,
          0.0
      ]
   },
   "colors" :
   {
      "blind" :
      [
          160,
          34,
          34,
          255

      ],
      "capped_force" :
      [
          160,
          34,
          160,
          255
      ],
      "default" :
      [
          34,
          160,
          34,
          255
      ]
   }
}
